modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/moostoet/pyrotech-1.21/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/moostoet/pyrotech-1.21"
authors="Moos Toet"
credits="Original mod by codetaylor (Pyrotech for Minecraft 1.12.2)"
description='''
Primitive technology. A port of codetaylor's Pyrotech from Minecraft 1.12.2 to NeoForge.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
